import numpy as np
print('')
print('')
print('-----------Start-----------')
print('')
print('Hello and Welcome Everyone to my 1D, 2D, 3D and 4D integer array producing app :)')
print('')
nam=input('Enter the dimension of the array (i.e. 1D, 2D, 3D and 4D):- ').lower()
print('')
if nam == '4d':
    n1=int(input('Enter the desired range of the array:- '))
    print('')
    n2=int(input('Enter the dimensions :- '))
    print('')
    n3=int(input('Enter the dimensions :- '))
    print('')
    n4=int(input('Enter the dimensions :- '))
    print('')
    n5=int(input('Enter the dimensions :- '))
    print('')
    arr4=np.arange(n1).reshape(n2,n3,n4,n5)
    print('')
    print('So the array is:-')
    print('')
    print(arr4)
    print('')
    print('You also see the type of array generated:-')
    print('')
    print(arr4.ndim,"Dimensional")
    print('')
    print('Order of the array you can get from it:-')
    print('')
    print(arr4.shape)
elif nam == '3d':
    n1=int(input('Enter the desired range of the array:- '))
    print('')
    n2=int(input('Enter the dimensions :- '))
    print('')
    n3=int(input('Enter the dimensions :- '))
    print('')
    n4=int(input('Enter the dimensions :- '))
    print('')
    arr4=np.arange(n1).reshape(n2,n3,n4)
    print('')
    print('So the array is:-')
    print('')
    print(arr4)
    print('')
    print('You also see the type of array generated:-')
    print('')
    print(arr4.ndim,"Dimensional")
    print('')
    print('Order of the array you can get from it:-')
    print('')
    print(arr4.shape)
elif nam == '2d':
    n1=int(input('Enter the desired range of the array:- '))
    print('')
    n2=int(input('Enter the dimensions :- '))
    print('')
    n3=int(input('Enter the dimensions :- '))
    print('')
    arr4=np.arange(n1).reshape(n2,n3)
    print('')
    print('So the array is:-')
    print('')
    print(arr4)
    print('')
    print('You also see the type of array generated:-')
    print('')
    print(arr4.ndim,"Dimensional")
    print('')
    print('Order of the array you can get from it:-')
    print('')
    print(arr4.shape)
elif nam == '1d':
    n1=int(input('Enter the desired range of the array:- '))
    print('')
    n2=int(input('Enter the dimensions :- '))
    print('')
    arr4=np.arange(n1).reshape(n2)
    print('')
    print('So the array is:-')
    print('')
    print(arr4)
    print('')
    print('You also see the type of array generated:-')
    print('')
    print(arr4.ndim,"Dimensional")
    print('')
    print('Order of the array you can get from it:-')
    print('')
    print(arr4.shape)
print('')
print('----------------End----------------')
print('')
print('')